[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
thiserror = "2.0.9"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "solver_benchmark"
harness = false
